### ISSUE TITLE
unexpected crash

### ISSUE THREAD

**Issue by SpeeD7Y** [SteveKunG/Indicatia#35]
[05Aug2021 16:47:57.841] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, ttxmtx, --version, 1.16.5-forge-36.1.0, --gameDir, C:\Users\revan\AppData\Roaming\.minecraft\1.16.5, --assetsDir, C:\Users\revan\AppData\Roaming\.minecraft\assets, --assetIndex, 1.16, --uuid, 4ff62abaa28932bd979096b4f1f09c6a, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.1.0, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[05Aug2021 16:47:57.846] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_51 by Oracle Corporation
[05Aug2021 16:47:57.868] [main/WARN] [cpw.mods.modlauncher.SecureJarHandler/]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[05Aug2021 16:47:58.030] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[05Aug2021 16:47:58.031] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\revan\AppData\Roaming\.minecraft\1.16.5\mods\OptiFine_1.16.5_HD_U_G7.jar
[05Aug2021 16:47:58.033] [main/INFO] [optifine.OptiFineTransformer/]: Target.PRE_CLASS is available
[05Aug2021 16:47:58.124] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[05Aug2021 16:47:58.165] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/revan/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[05Aug2021 16:47:58.170] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[05Aug2021 16:48:00.387] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[05Aug2021 16:48:00.430] [main/INFO] [optifine.OptiFineTransformer/]: Targets: 308
[05Aug2021 16:48:01.221] [main/INFO] [optifine.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[05Aug2021 16:48:01.424] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[05Aug2021 16:48:01.426] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [icyllis.modernui.forge.MixinConnector]
[05Aug2021 16:48:01.436] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.5-forge-36.1.0, --gameDir, C:\Users\revan\AppData\Roaming\.minecraft\1.16.5, --assetsDir, C:\Users\revan\AppData\Roaming\.minecraft\assets, --uuid, 4ff62abaa28932bd979096b4f1f09c6a, --username, ttxmtx, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release]
[05Aug2021 16:48:01.455] [main/INFO] [Indicatia MixinConfig/INFO]: OptiFine detected!
[05Aug2021 16:48:02.200] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'add_missing_tag_enchantment_tooltip' ASM patch...
[05Aug2021 16:48:02.268] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'add_missing_tag_enchantment_tooltip' ASM patch!
[05Aug2021 16:48:02.286] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'add_enchantment_tooltip' ASM patch...
[05Aug2021 16:48:02.310] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'add_enchantment_tooltip' ASM patch!
[05Aug2021 16:48:02.818] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'add_custom_entity_collision' ASM patch...
[05Aug2021 16:48:02.822] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'add_custom_entity_collision' ASM patch!
[05Aug2021 16:48:02.882] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'reach_set_server_entity_interact' ASM patch...
[05Aug2021 16:48:02.895] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'reach_set_server_entity_interact' ASM patch!
[05Aug2021 16:48:02.903] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'allow_entity_interaction' ASM patch...
[05Aug2021 16:48:02.919] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'allow_entity_interaction' ASM patch!
[05Aug2021 16:48:03.224] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'reach_set_client_renderer' ASM patch...
[05Aug2021 16:48:03.230] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'reach_set_client_renderer' ASM patch!
[05Aug2021 16:48:03.320] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'set_player_field' ASM patch...
[05Aug2021 16:48:03.324] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'set_player_field' ASM patch!
[05Aug2021 16:48:03.349] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'water_movement_slowdown_prevention' ASM patch...
[05Aug2021 16:48:03.352] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'water_movement_slowdown_prevention' ASM patch!
[05Aug2021 16:48:03.519] [main/INFO] [net.minecraftforge.coremod.CoreMod.observerlib/COREMODLOG]: Adding 'on_block_change' ASM patch...
[05Aug2021 16:48:03.545] [main/INFO] [net.minecraftforge.coremod.CoreMod.observerlib/COREMODLOG]: Added 'on_block_change' ASM patch!
[05Aug2021 16:48:03.551] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'sun_brightness_server' ASM patch...
[05Aug2021 16:48:03.554] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'sun_brightness_server' ASM patch!
[05Aug2021 16:48:03.644] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'add_enchantment_helper_levels' ASM patch...
[05Aug2021 16:48:03.658] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'add_enchantment_helper_levels' ASM patch!
[05Aug2021 16:48:03.663] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'add_enchantment_helper_enchantments' ASM patch...
[05Aug2021 16:48:03.667] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'add_enchantment_helper_enchantments' ASM patch!
[05Aug2021 16:48:03.670] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'add_enchantment_helper_apply_modifier' ASM patch...
[05Aug2021 16:48:03.672] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'add_enchantment_helper_apply_modifier' ASM patch!
[05Aug2021 16:48:03.762] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'add_missing_tag_enchantment_tooltip' ASM patch...
[05Aug2021 16:48:03.767] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'add_missing_tag_enchantment_tooltip' ASM patch!
[05Aug2021 16:48:03.768] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'add_enchantment_tooltip' ASM patch...
[05Aug2021 16:48:03.772] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'add_enchantment_tooltip' ASM patch!
[05Aug2021 16:48:05.138] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'add_custom_entity_collision' ASM patch...
[05Aug2021 16:48:05.139] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'add_custom_entity_collision' ASM patch!
[05Aug2021 16:48:05.160] [main/INFO] [net.minecraftforge.coremod.CoreMod.observerlib/COREMODLOG]: Adding 'on_block_change' ASM patch...
[05Aug2021 16:48:05.161] [main/INFO] [net.minecraftforge.coremod.CoreMod.observerlib/COREMODLOG]: Added 'on_block_change' ASM patch!
[05Aug2021 16:48:05.162] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'sun_brightness_server' ASM patch...
[05Aug2021 16:48:05.163] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'sun_brightness_server' ASM patch!
[05Aug2021 16:48:05.266] [main/INFO] [net.minecraftforge.coremod.CoreMod.observerlib/COREMODLOG]: Adding 'on_block_change' ASM patch...
[05Aug2021 16:48:05.266] [main/INFO] [net.minecraftforge.coremod.CoreMod.observerlib/COREMODLOG]: Added 'on_block_change' ASM patch!
[05Aug2021 16:48:05.267] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'sun_brightness_server' ASM patch...
[05Aug2021 16:48:05.267] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'sun_brightness_server' ASM patch!
[05Aug2021 16:48:05.280] [main/INFO] [net.minecraftforge.coremod.CoreMod.placebo/COREMODLOG]: Patching BlockModelShapes#getModelLocation
[05Aug2021 16:48:05.358] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'set_player_field' ASM patch...
[05Aug2021 16:48:05.359] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'set_player_field' ASM patch!
[05Aug2021 16:48:05.361] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'water_movement_slowdown_prevention' ASM patch...
[05Aug2021 16:48:05.361] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'water_movement_slowdown_prevention' ASM patch!
[05Aug2021 16:48:05.461] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'set_player_field' ASM patch...
[05Aug2021 16:48:05.461] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'set_player_field' ASM patch!
[05Aug2021 16:48:05.463] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'water_movement_slowdown_prevention' ASM patch...
[05Aug2021 16:48:05.463] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'water_movement_slowdown_prevention' ASM patch!
[05Aug2021 16:48:05.554] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'sun_brightness_client' ASM patch...
[05Aug2021 16:48:05.556] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'sun_brightness_client' ASM patch!
[05Aug2021 16:48:05.611] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'add_missing_tag_enchantment_tooltip' ASM patch...
[05Aug2021 16:48:05.612] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'add_missing_tag_enchantment_tooltip' ASM patch!
[05Aug2021 16:48:05.613] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Adding 'add_enchantment_tooltip' ASM patch...
[05Aug2021 16:48:05.613] [main/INFO] [net.minecraftforge.coremod.CoreMod.astralsorcery/COREMODLOG]: Added 'add_enchantment_tooltip' ASM patch!
[05Aug2021 16:48:05.973] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[05Aug2021 16:48:05.973] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[05Aug2021 16:48:05.973] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[05Aug2021 16:48:05.974] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[05Aug2021 16:48:05.974] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[05Aug2021 16:48:05.974] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[05Aug2021 16:48:05.974] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[05Aug2021 16:48:05.974] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[05Aug2021 16:48:05.975] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[05Aug2021 16:48:05.975] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[05Aug2021 16:48:05.975] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[05Aug2021 16:48:05.975] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[05Aug2021 16:48:05.975] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$494/334300782.call(Unknown Source)
[05Aug2021 16:48:05.975] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[05Aug2021 16:48:05.975] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[05Aug2021 16:48:05.976] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[05Aug2021 16:48:05.976] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[05Aug2021 16:48:05.976] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[05Aug2021 16:48:05.976] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[05Aug2021 16:48:05.976] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[05Aug2021 16:48:05.976] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[05Aug2021 16:48:05.976] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[05Aug2021 16:48:05.977] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[05Aug2021 16:48:05.977] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[05Aug2021 16:48:05.977] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[05Aug2021 16:48:05.977] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[05Aug2021 16:48:05.977] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[05Aug2021 16:48:05.977] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.Class.getDeclaredFields0(Native Method)
[05Aug2021 16:48:05.977] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
[05Aug2021 16:48:05.977] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.Class.getDeclaredFields(Class.java:1916)
[05Aug2021 16:48:05.977] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
[05Aug2021 16:48:05.978] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:501)
[05Aug2021 16:48:05.978] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:101)
[05Aug2021 16:48:05.978] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
[05Aug2021 16:48:05.978] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:425)
[05Aug2021 16:48:05.978] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(Main.java:122)
[05Aug2021 16:48:05.978] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	... 11 more
[05Aug2021 16:48:05.978] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method adjustOnPress(Lnet/minecraft/client/gui/widget/button/Button$IPressable;)Lnet/minecraft/client/gui/widget/button/Button$IPressable; in randompatches.mixins.json:client.IngameMenuScreenMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap randompatches.refmap.json
[05Aug2021 16:48:05.978] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[05Aug2021 16:48:05.979] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[05Aug2021 16:48:05.979] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[05Aug2021 16:48:05.979] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[05Aug2021 16:48:05.979] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[05Aug2021 16:48:05.979] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[05Aug2021 16:48:05.979] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[05Aug2021 16:48:05.980] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[05Aug2021 16:48:05.980] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	... 30 more

**Comment by SteveKunG** [comment]
Cannot reproduce an issue. I don't think its from Indicatia.
